apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: garnet-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: garnet-operator
subjects:
- kind: ServiceAccount
  name: garnet-operator
  namespace: '{{ .Release.Namespace }}'