apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: garnet-operator
rules:
- apiGroups:
  - ""
  resourceNames:
  - garnet-operator-webhook-tls
  resources:
  - secrets
  verbs:
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - '*'
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'