apiVersion: v1
kind: Service
metadata:
  name: {{ include "garnet-operator.fullname" . }}
  labels:
    {{- include "garnet-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
{{- if and .Values.metrics.enabled  }}
    - port: {{ .Values.metrics.port }}
      protocol: TCP
      name: http-metrics
      targetPort: {{ .Values.metrics.port }}
{{- end }}
  selector:
    {{- include "garnet-operator.selectorLabels" . | nindent 4 }}
